name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame mediapipe opencv-python numpy flake8

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=temp*.py
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=temp*.py
        
    - name: Check main script runs
      run: |
        python Tetris\ game/tetris_keyboard.py --help || true
