name: Python application

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame mediapipe opencv-python numpy flake8

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=temp*.py
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=temp*.py
        
    - name: Check main script runs
      run: |
        python Tetris\ game/tetris_keyboard.py --help || true

    - name: Create game artifact (zip)
      run: |
        zip -r tetris-game.zip "Tetris game"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tetris-game
        path: tetris-game.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: tetris-game

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: tetris-game.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
